package com.qlvb.mofa.dto.enums;

public enum SubmissionStatus {

    DRAFTING,
    REQUESTING_OPINION,
    SUBMITTING_UNIT_LEADER,
    APPROVED,
    WAITING_MINISTRY_LEADER,
    WAITING_SECRETARY_RECEIPT,
    WAITING_MINISTRY_LEADER_SIGN,
    MINISTRY_LEADER_SIGNED,
    WAITING_MINISTRY_OFFICE,
    PUBLISHED,

    DEPARTMENT_RETURNED,
    UNIT_LEADER_RETURNED,
    UNIT_OFFICE_RETURNED,
    MINISTRY_SECRETARY_RETURNED,
    MINISTRY_LEADER_RETURNED,
    MINISTER_RETURNED,
    MINISTRY_OFFICE_RETURNED,

    TRANSFERRED_TO_ORGANIZATION,

    REQUESTING_MINISTRY_LEADER_OPINION,
    MINISTRY_LEADER_SIGNED_REQUESTING_OPINION,
    SUBMITTING_MINISTRY_LEADER,

    REDONE,
    SUSPENDED
}